### PR TITLE
minimega: remove Panic at the Bridge Code

### LINKED ISSUE #299: minimega: panic in bridge code
Affects: master, 2.1

Running `minitest` twice against a running minimega instance causes a crash:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x409932]

goroutine 942 [running]:
runtime.panic(0xa9e660, 0x108d373)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
main.(*bridge).TapCreate(0xc2085908c0, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0)
        src/minimega/bridge.go:670 +0x662
main.(*KvmVM).launch(0xc208616d00, 0xc20816ba40, 0x0, 0x0)
        src/minimega/kvm.go:471 +0x6da
created by main.(*KvmVM).Start
        src/minimega/kvm.go:164 +0x340
```

Might be a race, seeing when there are a large number of existing minimega taps:

```
2015/08/26 22:01:46 WARN bridge.go:1228: tap mega_tap49 already exists, trying again
```

### PR DESCRIPTION
**Pull request by jcrussell**
Lots of refactoring of the bridge code. Needs a lot more testing before we merge this.

Once merged, fixes #299 and #303.

### CODE REVIEW

**Comment by djfritz** [comment]
Holy cow. I need a few days to ingest this.

**Comment by djfritz** [comment]
I should be able to get to this today or tomorrow. Can you pull master and get it merge-compatible again?

**Comment by jcrussell** [comment]
@djfritz: done.

**Comment by djfritz** [comment]
LGTM

**Pull request merged**
