### PR TITLE
minimega/novnc: update to novnc v0.6.1

### LINKED ISSUE #566: minimega: update novnc vendorized code, re-implement tunnel to use new standard
novnc used to use base64 encoded data over a websocket, now it does some other magic. #315 discusses this.

### PR DESCRIPTION
**Pull request by x64x6a**
Tested locally successfully. 
Could use more testing. Specifically, kb/fb recordings.

Closes #566

### CODE REVIEW

**Comment by x64x6a** [comment]
Locally, kb and fb recordings work.  Just need to test for cluster.

**Comment by jcrussell** [comment]
Hmm, something is not quite right:

```
util.js:218  Msg: noVNC ready: native WebSockets, canvas rendering
util.js:218 
util.js:218  Msg: Starting VNC handshake
util.js:218  Msg: Sent ProtocolVersion: 003.008
util.js:218  Msg: Authenticating using scheme: 1
util.js:218 
2
util.js:218  Msg: Authentication OK
util.js:218  Msg: Connected (unencrypted) to: QEMU (0)
28
rfb.js:572 Uncaught ReferenceError: XtScancode is not defined
rfb.js:572 Uncaught ReferenceError: XtScancode is not defined
_handleKeyPress	@	rfb.js:572
_handleRfbEvent	@	input.js:54
(anonymous function)	@	keyboard.js:381
process	@	keyboard.js:336
keydown	@	keyboard.js:342
_handleKeyDown	@	input.js:69
```

I added `xtscancodes.js` to the list passed to `Util.load_scripts` and now I'm seeing errors in qemu:

```
atkbd serio0 Unknown key pressed (translated set 2, code 0x0 on isa0060/serio0).
atkbd serio0: use `setkeycodes 00 <keycode>` to make it known.
atkbd serio0 Unknown key released (translated set 2, code 0x0 on isa0060/serio0).
atkbd serio0: use `setkeycodes 00 <keycode>` to make it known.
```

**Comment by x64x6a** [comment]
I downgraded to the 0.6.1 release and seemed to no longer get those errors.  The initial PR was from their latest commit.

**Comment by jcrussell** [comment]
Much better. I'm still seeing the `Unknown key pressed` error when hitting the `Windows` key. Other than that, appears to be working.

**Comment by x64x6a** [comment]
I don't seem to be able to recreate the `Windows` key issue

**Comment by jcrussell** [comment]
Maybe it's specific to the VM? I was connecting to a headless `minirouter` instance.

**Comment by x64x6a** [comment]
That might be a qemu/novnc issue in general, since I could recreate the `minirouter` issue with the old vnc  version as well.

**Comment by jcrussell** [comment]
Well, LGTM then.

**Pull request merged**
