### PR TITLE
minimega: fix #1300 vm config clone regression

### LINKED ISSUE #1300: bug: snapshot false unable to launch
**Describe your environment**

1. minimega version l- atest
2. Linux distro/version - ubuntu 16.04
3. Go compiler version - 1.10.2
4. VM types - kvm

**Describe the bug**
Launching with snapshot false errors

```
/A        | N/A      | N/A  | N/A     | N/A  | N/A    | N/A          | {"error":"qemu killed: exit status 1 QEMU waiting for connection on: disconnected:unix:/tmp/minimega/4/qmp,server\nqemu-system-x86_64: -drive file=/tmp/minimega/3/disk-0.qcow2,media=disk,if=ide,cache=writeback: Could not open '/tmp/minimega/3/disk-0.qcow2': No such file or directory\n"}
```

**To Reproduce**
```
vm config disk /mnt/storage/disk.qcow2
vm config snapshot false
vm launch kvm a
vm start a
```

**Expected behavior**
Vm launches without error

### PR DESCRIPTION
**Pull request by jasoncontrib**
Prevent `DiskConfig.SnapshotPath` from getting copied over upon `vm config clone`.

### CODE REVIEW

**Comment by djfritz** [comment]
@jcrussell @jasoncontrib If you clone a vm config will the cloned config get snapshots regenerated for the new VM or will it still point to the previous VM's snapshot paths?

**Comment by jasoncontrib** [comment]
@djfritz That was indeed the issue; the `SnapshotPath` was getting copied over in the `vm config clone`, and thus subsequently launched VMs had their disks pointed to the previous VM's snapshot disk. In the pull request, it's fixed so that snapshots are newly generated upon `vm launch` correctly after a `vm config clone`

**Comment by jasoncontrib** [comment]
@jcrussell @djfritz I made some more commits; do we think this is ready to merge?

**Comment by jcrussell** [comment]
LGTM. You could simplify the conflict check within a VM by checking it in the `ParseDiskConfig` loop ;)

Feel free to merge or change.

**Pull request merged**
