### PR TITLE
Web-based network rendering

### PR DESCRIPTION
**Pull request by jfktrey**
Force-directed graphs!
Fast WebGL rendering!
Visualize your network!

### CODE REVIEW

**Comment by djfritz** [comment]
I'll start testing this today.

**Comment by djfritz** [comment]
graph renders nothin in my tests. I have a setup with no VMs on the node running the webserver, and ~1500 VMs running on other connected nodes. It looks like maybe the problem is in the /json url. I'm getting this instead of info on all of the VMs:

    [{"host":"ccc10","id":0,"memory":"","name":"","network":null,"state":"VmState(0)","tags":null,"type":"???","vcpus":""},{"host":"ccc11","id":0,"memory":"","name":"","network":null,"state":"VmState(0)","tags":null,"type":"???","vcpus":""},{"host":"ccc12","id":0,"memory":"","name":"","network":null,"state":"VmState(0)","tags":null,"type":"???","vcpus":""},{"host":"ccc13","id":0,"memory":"","name":"","network":null,"state":"VmState(0)","tags":null,"type":"???","vcpus":""},{"host":"ccc14","id":0,"memory":"","name":"","network":null,"state":"VmState(0)","tags":null,"type":"???","vcpus":""},{"host":"ccc15","id":0,"memory":"","name":"","network":null,"state":"VmState(0)","tags":null,"type":"???","vcpus":""},{"host":"ccc16","id":0,"memory":"","name":"","network":null,"state":"VmState(0)","tags":null,"type":"???","vcpus":""},{"host":"ccc17","id":0,"memory":"","name":"","network":null,"state":"VmState(0)","tags":null,"type":"???","vcpus":""},{"host":"ccc18","id":0,"memory":"","name":"","network":null,"state":"VmState(0)","tags":null,"type":"???","vcpus":""},{"host":"ccc2","id":0,"memory":"","name":"","network":null,"state":"VmState(0)","tags":null,"type":"???","vcpus":""},{"host":"ccc3","id":0,"memory":"","name":"","network":null,"state":"VmState(0)","tags":null,"type":"???","vcpus":""},{"host":"ccc4","id":0,"memory":"","name":"","network":null,"state":"VmState(0)","tags":null,"type":"???","vcpus":""},{"host":"ccc5","id":0,"memory":"","name":"","network":null,"state":"VmState(0)","tags":null,"type":"???","vcpus":""},{"host":"ccc6","id":0,"memory":"","name":"","network":null,"state":"VmState(0)","tags":null,"type":"???","vcpus":""},{"host":"ccc7","id":0,"memory":"","name":"","network":null,"state":"VmState(0)","tags":null,"type":"???","vcpus":""},{"host":"ccc8","id":0,"memory":"","name":"","network":null,"state":"VmState(0)","tags":null,"type":"???","vcpus":""},{"host":"ccc9","id":0,"memory":"","name":"","network":null,"state":"VmState(0)","tags":null,"type":"???","vcpus":""}]

**Comment by jfktrey** [comment]
This should be ready for testing now. Issue with remote hosts was fixed.

**Comment by djfritz** [comment]
Testing this more today

**Comment by djfritz** [comment]
@jfktrey @jcrussell 

JSON url appears to be valid, but the graph still doesn't render anything, and now I'm getting errors on the default tab:

weberror

**Comment by jcrussell** [comment]
Seeing this outside of this PR... triaging.

**Comment by djfritz** [comment]
@jfktrey can you patch up the merge conflict in this branch now that I've merged some of @jcrussell 's other stuff?

**Comment by jfktrey** [comment]
Conflict should be resolved.

**Comment by djfritz** [comment]
LGTM

**Pull request merged**
