### PR TITLE
Meshage fix

### PR DESCRIPTION
**Pull request by floren**
Minimega used to only broadcast on one interface. Now, by default, it broadcasts on all ipv4 interfaces. If you specify "-interfaces eth0,eth1" it will only broadcast on eth0 and eth1.

@djfritz @jcrussell

### CODE REVIEW

**Comment by djfritz** [comment]
Looks like we enumerate broadcastAddrs once in NewNode(). What happens if the interface changes IP? Does it still work?

**Comment by floren** [comment]
I was just going to say "don't do that" but we can check at every broadcast
if needed. I wanted to avoid checking every single tap we create for vms,
but your point about changing ips makes sense

On Aug 3, 2016 3:16 PM, "David Fritz" <notifications@github.com> wrote:

Looks like we enumerate broadcastAddrs once in NewNode(). What happens if
the interface changes IP? Does it still work?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sandia-minimega/minimega/pull/610#issuecomment-237376395>,
or mute the thread

**Comment by djfritz** [comment]
What's the status on this? If the discussion is dead can we close this?

**Comment by floren** [comment]
Depends if we care about this functionality or not :)

**Pull request closed without merging**
