### PR TITLE
update to go 1.17; update dependencies

### PR DESCRIPTION
**Pull request by jacdavi**
updates version in `go.mod` to `1.17`.

updates `google/gopacket`, `miekg/dns`, `x/crypto`, and `x/net` dependencies incorporating PRs: #1497 #1496 #1495 and #1492

### CODE REVIEW

**Comment by jacdavi** [comment]
@aherna anything else for this?

**Comment by aherna** [comment]
> @aherna anything else for this?

Nope good to go

**Comment by jacdavi** [comment]
> > @aherna anything else for this?
> 
> Nope good to go

Cool. Can you approve it?

**Review by aherna — APPROVED** [review]
LGTM

**Pull request merged**
