### PR TITLE
misc: update ccc host image

### PR DESCRIPTION
**Pull request by jcrussell**
Include netcat-openbsd instead of regular netcat. Add curl.

### CODE REVIEW

**Comment by djfritz** [comment]
It may be the other way around:

    foo@foo:~$ nc -U
    This is nc from the netcat-openbsd package. An alternative nc is available
    in the netcat-traditional package.
    usage: nc [-46bCDdhjklnrStUuvZz] [-I length] [-i interval] [-O length]
              [-P proxy_username] [-p source_port] [-q seconds] [-s source]
              [-T toskeyword] [-V rtable] [-w timeout] [-X proxy_protocol]
              [-x proxy_address[:port]] [destination] [port]

**Comment by djfritz** [comment]
Did we confirm which version of netcat we really want?

**Comment by jcrussell** [comment]
I think we want netcat-traditional... I'll rebuild and test.

**Comment by floren** [comment]
netcat-openbsd is what we want. LGTM.

**Pull request merged**
