### PR TITLE
miniweb: clean up code, set record false, add `vm top` view

### PR DESCRIPTION
**Pull request by jcrussell**
Use sort.Slice to clean up some code. Made vmInfo cleaner and use in the
vms handler. Set record false so we don't clutter the history.

### CODE REVIEW

**Comment by jcrussell** [comment]
Failed tests because `sort.Slice` isn't in Go 1.7.

**Comment by djfritz** [comment]
Does travis have 1.8 yet? I have a hard time merging this even knowing it works because every PR moving forward will fail the tests...

**Comment by djfritz** [comment]
@jasoncontrib

**Comment by jasoncontrib** [comment]
It did pass in travis with Go 1.8: https://travis-ci.org/sandia-minimega/minimega/jobs/236451290

We probably want to remove 1.7.x from our travis config if we merge this, though, since that'll fail the whole travis build.

**Comment by jcrussell** [comment]
@djfritz -- changed travis config to remove 1.7 from tests.

**Comment by jcrussell** [comment]
@djfritz: PTAL, this should be ready to merge.

**Comment by jcrussell** [comment]
@jasoncontrib: PTAL at the `vm top` view.

**Pull request merged**
