### PR TITLE
[minimega] Recover VMs still running after a minimega crash

### PR DESCRIPTION
**Pull request by activeshadow**
This PR attempts to add support to minimega for recovering VMs after a crash. Currently, here's how it works:

* detects old unix socket still present
* `-recover` flag set (and `-force` flag not set)
* recovers previous VLAN alias --> ID mappings from file
* inspects namespaces directory for symbolic links to VM directories
* discovers running qemu processes that include a uuid flag matching one of the symbolic links
* follows symbolic link to VM directory and recovers config, taps, name, etc from files in VM directory
* creates new internal representations for running VMs without launching them again

Currently this only runs on the local node. This should be fine, since each node in a mesh would be responsible for their own recovery process.

### CODE REVIEW

**Comment by activeshadow** [comment]
@aherna this is still a work in progress, but it's finally coming along nicely. As of now, I can recover a VM that's still running, get everything to show up correctly in `vm info` table, connect to it over VNC, etc. There are still lots of edge cases that I haven't tested yet.

Just wanted to go ahead and get this in front of you.

**Comment by aherna** [comment]
> @aherna this is still a work in progress, but it's finally coming along nicely. As of now, I can recover a VM that's still running, get everything to show up correctly in `vm info` table, connect to it over VNC, etc. There are still lots of edge cases that I haven't tested yet.
> 
> Just wanted to go ahead and get this in front of you.

@jacdavi is going to get this review started

**Comment by activeshadow** [comment]
Sounds good @aherna.

@jacdavi as an FYI, I still need to support recovering VMs that were in the `BUILDING` stage when minimega crashed or otherwise went away suddenly. I also have not yet looked into recovering containers.

**Comment by jacdavi** [comment]
Yeah sorry, looking at it now.

Starting off with a simple test, I started minimega, started a vm (just configing disk) then ran `pkill -9 minimega -e`. 

Once restarting minimega with `-recover` I get an error `Unable to read taps file for vm 0: open /tmp/minimega/0/taps: no such file or directory` and it exits.

I'm guessing that's because I haven't made any taps, but it seems like if that's the case it shouldn't error out

**Comment by activeshadow** [comment]
> Yeah sorry, looking at it now.
> 
> 
> 
> I started minimega, started a vm (just configing disk) then ran `pkill -9 minimega -e`. 
> 
> 
> 
> Once restarting minimega with `-recover` I get an error `FATAL main.go:259: Unable to read taps file for vm 0: open /tmp/minimega/0/taps: no such file or directory` and it exits.
> 
> 
> 
> I'm guessing that's because I haven't made any taps, but it seems like if that's the case it shouldn't error out

Thanks! Easy fix. This is what I need... I had tested so many things while developing I couldn't remember what I hadn't tested.

I'll get this fixed tonight, along with anything else you find before then. 😂

**Comment by jacdavi** [comment]
Error above looks good now! I'll let you know if I figure out how to break anything else :)

**Comment by jacdavi** [comment]
I'm trying to recover our entire phenix experiment and get a seg fault. I'll try to debug some more, but you may know what the issue is quicker than me

```
./minimega/bin/minimega -context the-$HOSTNAME -filepath phenix/images -nostdin -recover -level debug

minimega, Copyright (2014) Sandia Corporation.
Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
the U.S. Government retains certain rights in this software.
2023/02/20 23:09:33 INFO external.go:241: kernel version: 4.15.0, minimum: 3.18
2023/02/20 23:09:33 INFO external.go:124: kvm found at: /usr/bin/kvm
2023/02/20 23:09:33 INFO external.go:124: tc found at: /sbin/tc
2023/02/20 23:09:33 INFO external.go:124: modprobe found at: /sbin/modprobe
2023/02/20 23:09:33 INFO external.go:124: dnsmasq found at: /usr/sbin/dnsmasq
2023/02/20 23:09:33 INFO external.go:124: dhclient found at: /sbin/dhclient
2023/02/20 23:09:33 INFO external.go:124: scp found at: /usr/bin/scp
2023/02/20 23:09:33 INFO external.go:124: ovs-vsctl found at: /usr/bin/ovs-vsctl
2023/02/20 23:09:33 INFO external.go:124: ovs-ofctl found at: /usr/bin/ovs-ofctl
2023/02/20 23:09:33 INFO external.go:124: ip found at: /sbin/ip
2023/02/20 23:09:33 INFO external.go:124: ssh found at: /usr/bin/ssh
2023/02/20 23:09:33 INFO external.go:124: qemu-img found at: /usr/bin/qemu-img
2023/02/20 23:09:33 INFO external.go:124: blockdev found at: /sbin/blockdev
2023/02/20 23:09:33 INFO external.go:124: tar found at: /bin/tar
2023/02/20 23:09:33 INFO external.go:124: mount found at: /bin/mount
2023/02/20 23:09:33 INFO external.go:124: cp found at: /bin/cp
2023/02/20 23:09:33 INFO external.go:124: ntfs-3g found at: /bin/ntfs-3g
2023/02/20 23:09:33 INFO external.go:124: taskset found at: /usr/bin/taskset
2023/02/20 23:09:33 INFO external.go:124: lsmod found at: /sbin/lsmod
2023/02/20 23:09:33 INFO external.go:124: qemu-nbd found at: /usr/bin/qemu-nbd
2023/02/20 23:09:33 DEBUG external.go:281: cmd dnsmasq completed in 5.048753ms
2023/02/20 23:09:33 INFO external.go:241: dnsmasq version: 2.79, minimum: 2.73
2023/02/20 23:09:33 DEBUG external.go:281: cmd ovs-vsctl completed in 2.970849ms
2023/02/20 23:09:33 INFO external.go:241: ovs-vsctl version: 2.9.0, minimum: 1.11
2023/02/20 23:09:33 DEBUG external.go:281: cmd kvm completed in 25.097428ms
2023/02/20 23:09:33 INFO external.go:241: qemu version: 2.11.1, minimum: 1.6
2023/02/20 23:09:33 DEBUG ovs.go:221: running ovs cmd: /usr/bin/ovs-vsctl set Open_vSwitch . other_config:vlan-limit=2
2023/02/20 23:09:33 INFO external.go:260: checking for kernel module: kvm
2023/02/20 23:09:33 DEBUG external.go:281: cmd lsmod completed in 2.333555ms
2023/02/20 23:09:33 INFO main.go:214: attempting to recover any vms from previous minimega instances
2023/02/20 23:09:33 INFO vlans.go:141: adding VLAN alias recovery//example => 101
...
2023/02/20 23:09:33 INFO main.go:230: recovering vms for namespace recovery
2023/02/20 23:09:33 INFO namespace.go:119: creating new namespace -- `recovery`
2023/02/20 23:09:33 INFO server.go:98: registered new ron server: phenix/images/recovery
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x6068e7]

goroutine 1 [running]:
github.com/sandia-minimega/minimega/v2/internal/meshage.(*Node).checkUpdateNetwork(0x0)
        /scratch/minimega/internal/meshage/node.go:593 +0x27
github.com/sandia-minimega/minimega/v2/internal/meshage.(*Node).BroadcastRecipients(0x0)
        /scratch/minimega/internal/meshage/message.go:183 +0x5f
main.NewNamespace({0xc0004870f9, 0x8})
        /scratch/minimega/cmd/minimega/namespace.go:167 +0x65f
main.GetOrCreateNamespace({0xc0004870f9, 0x8})
        /scratch/minimega/cmd/minimega/namespace.go:901 +0xc8
main.main()
        /scratch/minimega/cmd/minimega/main.go:232 +0x1349

**Comment by activeshadow** [comment]
Thanks @jacdavi I'll look into it more tonight.

**Comment by activeshadow** [comment]
@jacdavi looks like you're hitting this because I've yet to test recovering VMs from a namespace other than the default `minimega` namespace. I will need to relocate the recovery code to be run after the mesh has been started. Shouldn't be a big deal. I'll get a commit pushed out tonight or first thing tomorrow for you to redo this test against. Thanks!

**Comment by jacdavi** [comment]
Thanks for the quick updates! Ran the test again and I made it further. It looks like we get through recovering a number of VMs, but fail on `internet_router` (which is built from a phenix app).

Here's the error:
```
panic: assignment to entry in nil map

goroutine 1 [running]:
main.(*BaseConfig).ReadConfig(0xc00027d8b8, {0xa99020?, 0xc0003b7328?}, {0xc0002de479, 0x8})
        /scratch/minimega/cmd/minimega/vmconfiger_cli.go:1072 +0x1e5
main.(*VMConfig).ReadConfig(0xc00027d8b8, {0xa9ab88?, 0xc0003b7328}, {0xc0002de479, 0x8})
        /scratch/minimega/cmd/minimega/vmconfig.go:136 +0x65
main.recover()
        /scratch/minimega/cmd/minimega/recovery.go:56 +0x58b
main.main()
        /scratch/minimega/cmd/minimega/main.go:251 +0xf3b
```


I tested a quick fix by adding this to `vmconfiger_cli#ReadConfig` and it fixed the error. No crashes after that though I didn't see things come back up. I'll look into why that was more tomorrow

```
// Initialize tags, if not already
if v.Tags == nil {
    v.Tags = map[string]string{}
}
```

**Comment by jacdavi** [comment]
Ok sounds good. You might be able to move the map initialization up the call stack, I just tried there because it was easiest.

**Comment by activeshadow** [comment]
> Ok sounds good. You might be able to move the map initialization up the call stack, I just tried there because it was easiest.

Yeah, that's an option I was going to look into as well. :+1:

**Comment by activeshadow** [comment]
> I tested a quick fix by adding this to `vmconfiger_cli#ReadConfig` and it fixed the error. No crashes after that though I didn't see things come back up. I'll look into why that was more tomorrow

@jacdavi were you able to do anymore testing to see if things come back up after recovering from a crash?

**Comment by jacdavi** [comment]
Yeah, so I'm not seeing any errors, but just not seeing anything recover either. I can send you the full logs

**Comment by jacdavi** [comment]
Ok, after teaching me about namespaces, I haven't seen any issues. @aherna after recovery miniccc works fine for send/exec/mnt

**Comment by activeshadow** [comment]
Sweet! @aherna and @jacdavi I'll get the commits for this PR squashed and ready for merging ASAP. 👍🏻

**Comment by activeshadow** [comment]
@aherna @jacdavi okay I think this is ready for final review and merge!

**Comment by jacdavi** [comment]
@activeshadow did you make any additional changes before squashing? I grabbed a new copy of the branch and am seeing an issue where things recover, but the VMs are mixed up (at least for VNC) in phenix/miniweb.

**Comment by activeshadow** [comment]
> @activeshadow did you make any additional changes before squashing? I grabbed a new copy of the branch and am seeing an issue where things recover, but the VMs are mixed up (at least for VNC) in phenix/miniweb. 

Nope no changes @jacdavi just squashed commits.

**Comment by jacdavi** [comment]
Ok, I _think_ I found the issue. In `recovery.go` we create a new VM then afterwards reset the ID. But that doesn't appear to update the `instancePath` variable, so the files are in the wrong location.

I was consistently having VNC mixed up, but have not seen the issue after adding this line to recovery.go line 136 
```
			kvm.instancePath = filepath.Join(*f_base, vm.VMID)
```


Also, it appears that tags aren't being recovered correctly. For example `{"device-type":"server","name":"miniserver7"}` turns into `{"tags":"name"}` after recovery. I haven't looked at a fix for this yet.

Sorry I didn't find these earlier!

**Comment by activeshadow** [comment]
@jacdavi okay, both issues should be fixed now.

**Comment by activeshadow** [comment]
@jacdavi @aherna I just now rebased this branch on top of the master branch.

Any updates on when you'll be able to test this again so we can put a bow on it?

**Comment by jacdavi** [comment]
Hey Bryan,

I’ve been out of town this week, but I’ll test asap on Monday. Sorry for the delay!
________________________________
From: Bryan Richardson ***@***.***>
Sent: Thursday, March 9, 2023 1:54:25 PM
To: sandia-minimega/minimega ***@***.***>
Cc: Davis, Jacob ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [sandia-minimega/minimega] [minimega] Recover VMs still running after a minimega crash (PR #1493)


@jacdavi<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjacdavi&data=05%7C01%7Cjacdavi%40sandia.gov%7C028826fa3be04b9d231c08db20e8de19%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C638139956753282142%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=erCFHqSvVESPWZqpdk8o4535psqN2PxcQXB5SlolPaQ%3D&reserved=0> @aherna<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faherna&data=05%7C01%7Cjacdavi%40sandia.gov%7C028826fa3be04b9d231c08db20e8de19%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C638139956753282142%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3NaXM7syIUhoecP4zm6xvuwGjsO%2B1NLiEw%2BiLf%2FVpMU%3D&reserved=0> I just now rebased this branch on top of the master branch.

Any updates on when you'll be able to test this again so we can put a bow on it?

**Comment by jacdavi** [comment]
Ok, it looks like our AD server isn't getting an IP address despite it being statically defined in the phenix topology. It seems to work fine with the earlier version I have of the PR (just before the first squash). I switched back and forth a few times and found it to be consistent.

I briefly checked the tags and VNC paths and those seem fixed.

**Comment by activeshadow** [comment]
@jacdavi whoa... that's interesting. I'm assuming that's not the only Windows VM you're deploying? Are the other VMs getting their IPs or are they DHCP?

I don't recall changing the Windows startup script inject, so I'll have to go back and take a look.

More to come.

**Comment by jacdavi** [comment]
It appears to just be windows VMs getting an IP of `0.0.0.0`. Our statically assigned linux VMs look fine. If you need to take a look at our environment, feel free

**Review by jacdavi — APPROVED** [review]

**Comment by jacdavi** [comment]
> It appears to just be windows VMs getting an IP of `0.0.0.0`. Our statically assigned linux VMs look fine. If you need to take a look at our environment, feel free

For reference, this issue seems to have been introduced with #1494, but was only noticed while testing this PR. Everything here works as expected.

**Comment by activeshadow** [comment]
Thanks for merging @jacdavi! I should have squashed my commits one more time before you did. My bad...

**Comment by jacdavi** [comment]
@activeshadow thank you for all of your work and help on this! I don't think squashing matters too much, I probably had an option to squash on merge, but I forgot to check ¯\_(ツ)_/¯

**Pull request merged**
