### PR TITLE
minimega: call logSetup and cliSetup before tests.

### LINKED ISSUE #310: tests: vm inject
Getting an invalid command on the build:

    --- FAIL: TestParseInject (0.00s)
            qcow_test.go:24: invalid command: vm inject src src.qc2 "my file":"Program Files/my file"

Please triage.

@jcrussell

### PR DESCRIPTION
**Pull request by jcrussell**
Need to register handlers before trying to run tests. Fixes #310.

### CODE REVIEW

**Comment by djfritz** [comment]
This will probably break the containers branch:

https://github.com/djfritz/minimega/blob/containers/src/minimega/main.go#L73

containerShim() does a different kind of log setup by dup2'ing an inherited fd from the calling minimega. To work around this, the shim could undo what logSetup does, but that seems like a hack.

**Comment by jcrussell** [comment]
It won't affect the shim -- it's only used for running tests.

**Comment by djfritz** [comment]
Woops. I didn't look at the filename and inferred that you moved the log setup into init() in minimega's main.go. I am a potato.

**Comment by djfritz** [comment]
LGTM

**Pull request merged**
