### PR TITLE
various: send cc files in chunks

### PR DESCRIPTION
**Pull request by jcrussell**
Instead of reading and sending the file in a single message, split it
across several. This allows you to send and recv files that exceed the
size of VM memory.

Seems to work for the updated test case, needs more testing though.

Updates #1262.

### CODE REVIEW

**Comment by jcrussell** [comment]
`cc_io` test fails, needs triage.

**Comment by djfritz** [comment]
@jcrussell status on this?

**Comment by djfritz** [comment]
@jcrussell should we just merge and test on master since this is passing tests?

**Comment by jcrussell** [comment]
I haven't had a chance to triage why the `cc_io` test was failing sometimes. Could merge with the expectation of having to triage a bit.

**Comment by djfritz** [comment]
That's probably the best route...

**Pull request merged**
