### PR TITLE
minimega: fix #1336

### LINKED ISSUE #1336: minimega: clogged containers
**Describe your environment**

1. minimega version: master
2. Linux distro/version: debian testing
3. Go compiler version: N/A
4. VM types: container

**Describe the bug**

Getting this error message on flush:

```ERROR vms.go:359: clogged vm 1: remove /tmp/minimega/namespaces/minimega/b03c6f48-71c5-4169-82c4-5749d0f8efa3: no such file or directory```

Possibly related to #1287.

**To Reproduce**

```
vm config filesystem /path/to/filesystem
vm launch container 1
vm kill all
vm flush
```

**Expected behavior**

No error message. Doesn't seem to be polluting filesystem though.

### PR DESCRIPTION
**Pull request by jasoncontrib**
create VM instance path symlinks for containers, too

### CODE REVIEW

**Comment by jcrussell** [comment]
If the MkdirAll/Symlink fail, the VM will still be in the running state (and not error). It's probably fine, how often do those calls fail?

**Comment by djfritz** [comment]
If you have the base directory in a special filesystem that doesn't allow symlinks (NFS, etc). There are lots of filesystems that this would go bonkers on.

**Comment by djfritz** [comment]
... Now that said you probably wouldn't get this far because I bet any FS that doesn't support symlinks also won't allow a UDS, which mini tries to create early in main().

**Comment by djfritz** [comment]
What if the symlink still existed from a prior broken run or something - shouldn't we bail?

**Comment by jasoncontrib** [comment]
> If the MkdirAll/Symlink fail, the VM will still be in the running state (and not error). It's probably fine, how often do those calls fail?

If it fails, it should still return an error through the `errs` channel just like any of the other potential errors in that section? Do those also leave the VM in the `RUNNING` state?

> What if the symlink still existed from a prior broken run or something - shouldn't we bail?

Do you mean if a `namespaces\<namespace>` directory still exists from a prior run, we should bail? The subdirectories under that are UUIDs, so there shouldn't be collisions, but yeah we could bail if the `namespaces` folder exists at all, if that's the behavior we want.

**Comment by djfritz** [comment]
nono - just if somehow the uuid or something already existed - which could happen if you were using `vm config uuid`

@jcrussell

**Comment by jcrussell** [comment]
minimega doesn't allow you to launch two VMs in the same namespace with the same UUID.

**Comment by jasoncontrib** [comment]
> What if the symlink still existed from a prior broken run or something - shouldn't we bail?

So this is addressed in the last commit now.

> If the MkdirAll/Symlink fail, the VM will still be in the running state (and not error). It's probably fine, how often do those calls fail?

@jcrussell Is this true? From my tests, if I introduce an error in MkdirAll/Symlink, it stays in `BUILDING` state, same as it would for other errors in that section?

**Comment by jcrussell** [comment]
Err, yeah, I meant `BUILDING` not `RUNNING`.

I guess the question is, if the MkdirAll/Symlink fail, are we fine with an error being printed but the VM not being in the `ERROR` state.

**Comment by jasoncontrib** [comment]
That applies not just to MkdirAll/Symlink, but also to writeVMConfig errors, right? Could we just set the vm state to `ERROR` if any of those fail?

**Comment by jcrussell** [comment]
True, we might want to set the state if any of the three fail. Or, we could ignore it since the VM is functioning otherwise. Not sure.

@djfritz

**Comment by djfritz** [comment]
I think it should head to `ERROR` - if we have scripting that depends on the symlink stuff outside of minimega, we should be able to catch errors at boot time. 

It sounds like it's hard to do that now? How does `Launch()` bail on other errors now?

**Comment by jasoncontrib** [comment]
@djfritz sounds good, the latest commit has it go to "ERROR" state now.

**Comment by jcrussell** [comment]
LGTM

**Comment by djfritz** [comment]
Several things here are still broken somehow:

1. Some kind of race - when reading a .mm script, no containers get launched and instead I get "cgroups not ready". When I turn on debug logging, the same script works fine...

2. "quit" still takes several minutes to complete, even with just a few hundred containers on a single node. With 2.5-release, the same action is a few seconds.

**Comment by jasoncontrib** [comment]
>     2. "quit" still takes several minutes to complete, even with just a few hundred containers on a single node. With 2.5-release, the same action is a few seconds.

@djfritz I don't believe the slowness was introduced by #1287, `quit` is slow on the parent commit b0e51e27 to that merge as well,

**Comment by djfritz** [comment]
Hmm then we should find that regression and file an issue. It's taking 1 second per container to clean up an experiment. Having 8000 containers on a node and trying to `clear all` is painful...

**Comment by jasoncontrib** [comment]
e28b548313016ec8cd12a889730106955760093f is the commit that introduced the slowness you're seeing. However, it's also the commit that fixed  `ERROR vms.go:357: clogged VM: overlay unmount: device or resource busy` upon quitting containers...

**Comment by jasoncontrib** [comment]
@djfritz I'm not able to reproduce

> Some kind of race - when reading a .mm script, no containers get launched and instead I get "cgroups not ready". When I turn on debug logging, the same script works fine...

Can you send me the .mm script with which you're seeing that issue?

**Comment by djfritz** [comment]
The "cgroups not ready" was a stuck node of mine, so disregard that. I'd like to test this with #1353 and then merge.

**Comment by djfritz** [comment]
Tested with #1353 - seems to work. Quitting with 100 running containers only takes 1.34s.

@jcrussell @jasoncontrib any other hangups before merging?

**Comment by jcrussell** [comment]
I think it's ready to merge.

**Pull request merged**
