### PR TITLE
minimega: cliPreprocessor improvements

### PR DESCRIPTION
**Pull request by jcrussell**
Prepend all commands from Namespace.Launch with the namespace. This
ensures that we invoke the cliPreprocessor.

Updates #555.

### CODE REVIEW

**Comment by jcrussell** [comment]
Something still isn't right...

**Comment by djfritz** [comment]
@jcrussell is this ready?

**Comment by jcrussell** [comment]
Yeah, this is ready.

**Comment by jcrussell** [comment]
Shoot... definitely didn't want to close this.

@djfritz: this is ready.

**Comment by djfritz** [comment]
Well here we go. LGTM

**Pull request merged**
