### PR TITLE
noVNC - Now with more buttons

### PR DESCRIPTION
**Pull request by mkunz7**
Simplifies code.

Enables scaling, mobile keyboard, mobile l/m/r click, viewport, and more.
Clipboard is hidden because QEMU sockets do not provide functionality.

novnc

### CODE REVIEW

**Comment by x64x6a** [comment]
doesn't work for me
novnc

**Comment by mkunz7** [comment]
clear cache

**Comment by x64x6a** [comment]
It work's if I open it in incognito..
novnc1

**Comment by x64x6a** [comment]
The settings menu seems sort of useless though?  Should you hide it?
Also, the icon they have for alt+ctrl+del isn't very obvious..

**Comment by mkunz7** [comment]
If you disconnect you can use it to change the things like scaling mode.

**Comment by mkunz7** [comment]
The websocket for novnc doesn't close switching between machines. Closing the browser seems to be the only way. Hold off on the merge.

**Comment by mkunz7** [comment]
Fixed the websocket issue, should be safe to merge.

**Comment by djfritz** [comment]
@mkunz7 can you bring this up to HEAD and we'll figure out getting this in.

**Pull request closed without merging**
