### PR TITLE
VM++

### PR DESCRIPTION
**Pull request by jcrussell**
Lots of refactoring to address tickets #165 and #179.

Needs lots of testing before we should actually merge it.

### CODE REVIEW

**Comment by jcrussell** [comment]
TODO: Populate a CC active field in the VM so that it's available over mesh.

**Comment by jcrussell** [comment]
@djfritz: I think this is ready for you to start hammering on. There's quite a bit more work to do on minitest but I don't have time to extend it right now -- perhaps an intern can take over?

**Comment by djfritz** [comment]
I'll start work on this today.

**Comment by djfritz** [comment]
2015/06/16 08:01:37 FATAL apigen.go:58: invalid character 'h' looking for beginning of value

This happens with vm++ when invoking apigen in the build script.

**Comment by djfritz** [comment]
Starting to test:

2015/06/25 20:14:49 ERROR command_meshage.go:131: gob: type not registered for interface: main.vmKVM

**Comment by djfritz** [comment]
with the latest patch, on

   mesh send all vm info

I get 

   2015/06/26 21:01:01 ERROR client.go:80: client ccc2 decode: gob: main.vmKVM is not assignable to type main.VM

**Comment by djfritz** [comment]
panic: send on closed channel
    
    goroutine 1038 [running]:
    ipmac.(*IPMacLearner).learner(0xc208219820)
            /home/djfritz/repos/real_minimega/src/ipmac/ipmac.go:119 +0x419
    created by ipmac.NewLearner
            /home/djfritz/repos/real_minimega/src/ipmac/ipmac.go:53 +0x2cd

**Comment by djfritz** [comment]
One last test then I'm merging this today.

**Comment by djfritz** [comment]
LGTM

**Pull request merged**
