### PR TITLE
Vendorize me

### PR DESCRIPTION
**Pull request by devinc**

### CODE REVIEW

**Comment by floren** [comment]
The pull request that adds 12,000 lines of Python... this is gonna wreck our ideological purity :)

**Comment by devinc** [comment]
blame @djfritz... I was fine leaving it out

**Comment by jcrussell** [comment]
Our go purity is only 78.6%, need to drop that 18.5% JavaScript.

**Comment by bjwrigh** [comment]
most of the JS is the novnc stuff.... just saying.

**Comment by djfritz** [comment]
Long discussion with Vince, other things coming, punting this.

**Pull request closed without merging**
