### PR TITLE
minimega: fix races and refactoring

### PR DESCRIPTION
**Pull request by jcrussell**
Lots of refactoring to fix several known races and a few potential races. Most of the work went into ensuring that all uses of `vms` are synchronized using `vmLock`. Moved all uses of `vmLock` to `vmlist.go` and followed naming convention for all `VMs` methods:

 * capitalized (would-be exported) functions acquire `vmLock`
 * lower-cased functions assume `vmLock` is held by caller

Also used `go install -race minimega` to identify two other data races which are now fixed. This passes all the `minitest` cases -- I think it should be at least as stable as master.

### CODE REVIEW

**Comment by jcrussell** [comment]
Passes all the new minitests.

**Comment by jcrussell** [comment]
Don't merge: this hung when I tried launching an enterprise-level experiment.

**Comment by jcrussell** [comment]
This is finally ready to merge.

@djfritz

**Comment by djfritz** [comment]
Working on this today.

**Comment by djfritz** [comment]
Cursory review LGTM. I'll do some random tests on it, but this looks like it's well captured in minitest.

**Comment by djfritz** [comment]
LGTM

**Pull request merged**
