### PR TITLE
minimega,qmp: add "force" option to vm cdrom eject

### LINKED ISSUE #1256: minimega: vm cdrom change buggy in osx
```2019/02/20 11:44:37 DEBUG command_socket.go:180: got request over socket: {vm cdrom change hs /home/ubuntu/test.iso   }
2019/02/20 11:44:37 DEBUG vms.go:477: applying main.(*VMs).Apply to hs
2019/02/20 11:44:37 DEBUG qmp.go:116: qmp write: map[string]interface {}{"execute":"eject", "arguments":map[string]interface {}{"device":"ide0-cd0"}}
2019/02/20 11:44:37 DEBUG qmp.go:111: qmp read: map[string]interface {}{"error":map[string]interface {}{"class":"GenericError", "desc":"Device 'ide0-cd0' is locked and force was not specified, wait for tray to open and try again"}}
```
osx >= high sierra doesn't like how we insert and remove isos and I have to manually unmount the drive in order to unlock the device for qemu to handle the switch. Perhaps the force flag should be an option.
```
diskutil list
diskutil eject disk1
diskutil eject disk2
```
```
vm cdrom change hs /home/ubuntu/test.iso
```

### PR DESCRIPTION
**Pull request by jcrussell**
Allow override of guest's "locked" cdrom. Needs testing.

Fixes #1256.

### CODE REVIEW

**Comment by jcrussell** [comment]
@mkunz7: can you test that this works for you?

**Comment by mkunz7** [comment]
change needs a force as well...

It didn't seem to help osx though, I still have to run those commands to eject the disk before ejecting in mini and and before changing iso

**Comment by jcrussell** [comment]
Does the debug log still look like:

```
2019/02/20 11:44:37 DEBUG qmp.go:116: qmp write: map[string]interface {}{"execute":"eject", "arguments":map[string]interface {}{"device":"ide0-cd0"}}
2019/02/20 11:44:37 DEBUG qmp.go:111: qmp read: map[string]interface {}{"error":map[string]interface {}{"class":"GenericError", "desc":"Device 'ide0-cd0' is locked and force was not specified, wait for tray to open and try again"}}
```

Or can you see the "force" parameter in the arguments?

**Comment by mkunz7** [comment]
Just tested the latest, the force function works. Thank you. You still need to run the os commands to release the drive though. This will have to work for now until qemu patches the function they call to tell the os the drive has been ejected.

**Comment by mkunz7** [comment]
if http://philjordan.eu/osx-virt/ ever writes the virtio-scsi driver for osx I think you could hotplug scsi cdroms from hmp

```
device_add virtio-scsi-pci
drive_add 0 file=/home/ubuntu/a.iso,if=none,id=test,readonly=on,format=raw
device_add scsi-cd,drive=test
```

**Pull request merged**
