### PR TITLE
WIP: changing heiarchy to golang-standards/project-layout. compiles on go1.13+

### PR DESCRIPTION
**Pull request by chengsteven**
WIP: reorganize code to follow https://github.com/golang-standards/project-layout. Note, it's not an official standard defined by the Go dev team (since it looks like there is no standard) but it is an emerging layout pattern in the go ecosystem.

### CODE REVIEW

**Comment by aherna** [comment]
@chengsteven is this ready to be reviewed or do you need more time?

**Comment by chengsteven** [comment]
It can be reviewed. More changes can be made to truly follow that project layout but want to see if this is even desirable first

**Comment by activeshadow** [comment]
@aherna @chengsteven I have an updated version of the branch for this PR that I've rebased onto the current master branch and resolved conflicts for. It would be great to get this tested and merged to make development of minimega easier.

**Comment by activeshadow** [comment]
@aherna @chengsteven I should mention that I named my branch `go-modules`. I can create a new PR for it if that would make things easier.

**Comment by activeshadow** [comment]
This PR can be closed. A different PR addressing this was already approved and merged.

**Comment by aherna** [comment]
Already Done in #1464

**Pull request closed without merging**
