### PR TITLE
minimega: add `check` flag to `read`

### PR DESCRIPTION
**Pull request by jcrussell**
`validate` reads a mm script and validates the syntax of the commands
therein. Only checks syntax and not semantics.

### CODE REVIEW

**Comment by djfritz** [comment]
LGTM, but was is this used for?

**Comment by jcrussell** [comment]
I generated a `launch.mm` script using a `launch.bash` script and I wanted to check that all the commands would compile before I ran it. We could merge this into the `read` API and have an optional flag to validate but not run the commands.

**Comment by jcrussell** [comment]
Updated to add a flag to `read`. Much fewer LoC for the same functionality.

**Comment by djfritz** [comment]
LGTM

**Pull request merged**
