### PR TITLE
minimega: implement smarter scheduler

### PR DESCRIPTION
**Pull request by jcrussell**
Implements a least loaded first scheduler. Added two new APIs:

```
vm config schedule [host]
vm config coschedule [num]
```

TODO:
- [x] Add `nsmod` to change load calculation
- [x] Add documentation
- [x] Refactor after merging #815 
- [x] Test with existing models

Updates #536.

### CODE REVIEW

**Comment by jcrussell** [comment]
Tried playing with this today, needs some tweaking before we merge.

**Comment by jcrussell** [comment]
I think we should probably merge #815 first since it will clean up quite a bit of the scheduler code.

**Comment by jcrussell** [comment]
This scheduler won't abort if all the available machines exceed a specified commit load. We should probably allow users to configure a limit and abort if all the machines exceed it. Do we want to do that in this PR or add it afterwards?

@djfritz

**Comment by djfritz** [comment]
We should certainly consider a healthy abort condition in this PR - probably time based. This probably needs to be a tunable as well. A simple watchdog should suffice - if no progress is made in X seconds, abort.

**Comment by jcrussell** [comment]
I guess we could do something time based. While the scheduler beams out VMs, it could check how long machines are taking to respond that they launched the VM and abort if that takes too long. The experiment could still blow up when you call `vm start`.

Alternatively, the scheduler is static so couldn't the abort be static too? We keep track of the VCPU/memory/network commit per-machine as we schedule VMs -- if all the machine exceed Nx commit, abort. We could support per-resource commit limits (e.g. CPU is okay at 8x, memory is okay at 4x).

**Comment by jcrussell** [comment]
@djfritz -- punting on the abort condition, will address later.

**Pull request merged**
