### PR TITLE
doc: initial draft of 2.2 release notes.

### PR DESCRIPTION
**Pull request by jcrussell**
Think it's mostly complete, need to make another pass through the diff between HEAD and 2.1.

### CODE REVIEW

**Comment by djfritz** [comment]
I have this started from a few weeks ago as well.

**Comment by jcrussell** [comment]
Things to add:

* Nuke improvements (?)
* Configurable cc port (?)
* New `vm config tag` API
* disk API changes for base path
* UUID uniqueness

**Comment by djfritz** [comment]
I'm pulling this into the doc I started already and refreshing from the history since we started this. I should have a new PR along with two other docs soon.

**Comment by jcrussell** [comment]
Copied into a different branch, closing this one.

**Pull request closed without merging**
