### PR TITLE
powerbot: Remove an unused source file from powerbot

### PR DESCRIPTION
**Pull request by mwisely**
`ssh.go` isn't used anywhere in powerbot. It'll build without it.

### CODE REVIEW

**Comment by djfritz** [comment]
How on earth did we hit a merge conflict with this... Will merge after it gets updated.

**Comment by mwisely** [comment]
Hmm. I'm on it.

**Comment by mwisely** [comment]
@djfritz I think it's good now. I'm not sure what happened.

**Comment by jcrussell** [comment]
FWIW, the merge conflict was due to changes in the way we vendorized code.

**Pull request merged**
