### PR TITLE
miniweb: add minimega console

### PR DESCRIPTION
**Pull request by jcrussell**
_WIP: Suggestions welcome._

Added minimega console. Mostly functional. Terminal width is a bit
wonky. Tabbed completion doesn't work. minimega location is hardcoded to
bin/minimega.

Updates #871

### CODE REVIEW

**Comment by jasoncontrib** [comment]
Pretty cool! Also, pressing up arrow shows keycode instead of previous command(s).

**Comment by jcrussell** [comment]
Played with the container console a bit -- both tabbed completion and arrow keys work there.

I replaced `bin/minimega -attach` with `bash -l` in `consoleHandler` and that also works. Seems like it must be an issue with liner.

**Comment by jcrussell** [comment]
This is likely an issue with raw vs cooked mode.

**Comment by jcrussell** [comment]
Dumped the terminal settings before/after `ApplyMode` in liner. In xterm:

```
Old mode: &liner.termios{Termios:syscall.Termios{Iflag:0x4500, Oflag:0x5,
Cflag:0xbf, Lflag:0x8a3b, Line:0x0, Cc:[32]uint8{0x3, 0x1c, 0x7f, 0x15, 0x4,
0x0, 0x1, 0x0, 0x11, 0x13, 0x1a, 0x0, 0x12, 0xf, 0x17, 0x16, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
Pad_cgo_0:[3]uint8{0x0, 0x0, 0x0}, Ispeed:0x0, Ospeed:0x0}}

New mode: &liner.termios{Termios:syscall.Termios{Iflag:0x4000, Oflag:0x5,
Cflag:0xbf, Lflag:0xa31, Line:0x0, Cc:[32]uint8{0x3, 0x1c, 0x7f, 0x15, 0x4,
0x0, 0x1, 0x0, 0x11, 0x13, 0x1a, 0x0, 0x12, 0xf, 0x17, 0x16, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
Pad_cgo_0:[3]uint8{0x0, 0x0, 0x0}, Ispeed:0x0, Ospeed:0x0}}
```

In xterm.js: 

```
Old mode: &liner.termios{Termios:syscall.Termios{Iflag:0x500, Oflag:0x5,
Cflag:0xbf, Lflag:0x8a3b, Line:0x0, Cc:[32]uint8{0x3, 0x1c, 0x7f, 0x15, 0x4,
0x0, 0x1, 0x0, 0x11, 0x13, 0x1a, 0x0, 0x12, 0xf, 0x17, 0x16, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
Pad_cgo_0:[3]uint8{0x0, 0x0, 0x0}, Ispeed:0x0, Ospeed:0x0}} 

New mode: &liner.termios{Termios:syscall.Termios{Iflag:0x0, Oflag:0x5,
Cflag:0xbf, Lflag:0xa31, Line:0x0, Cc:[32]uint8{0x3, 0x1c, 0x7f, 0x15, 0x4,
0x0, 0x1, 0x0, 0x11, 0x13, 0x1a, 0x0, 0x12, 0xf, 0x17, 0x16, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
Pad_cgo_0:[3]uint8{0x0, 0x0, 0x0}, Ispeed:0x0, Ospeed:0x0}} 
```

The only difference I see is IUTF8 (0x4000).

**Comment by jcrussell** [comment]
Figured out the issue after a lot of digging. xterm.js can't resize the pty without help (it can't send SIGWINCH). xterm.js has an example:

Client: [main.js](https://github.com/sourcelair/xterm.js/blob/7645bdd418b37a8bd176a69179c06178c8cb1130/demo/main.js#L79-L88)
Server: [app.js](https://github.com/sourcelair/xterm.js/blob/7645bdd418b37a8bd176a69179c06178c8cb1130/demo/app.js#L45-L54)

Basically, we need to add a resize API to miniweb to pass the resize to the pty.

**Comment by floren** [comment]
Can we put this behind a -console flag in miniweb for now, default to off? As it is, running miniweb puts what is essentially a root shell out on :9001 for the world to see (if you don't have a firewall set up), and I feel like that's just asking for trouble with unsophisticated users. I accept that KVM/container breakout from the web consoles is also a possibility but at least there's a slight barrier to entry!

Obvious next step would be to put some sort of authentication into miniweb, then we could default to enabling the console.

**Comment by floren** [comment]
(otherwise it looks awesome and works fine for me)

**Pull request merged**
