### PR TITLE
[minimega] Support QinQ between VMs

### PR DESCRIPTION
**Pull request by activeshadow**
Add `qinq` option to VM network specification config that sets the VLAN mode to `dot1q-tunnel` for the network tap in Open vSwitch.

### CODE REVIEW

**Comment by activeshadow** [comment]
@aherna any thoughts on how to depict the QinQ setting for a VM in `vm info`? Should I modify the existing `vlan` column to include `qinq` for a particular VLAN? Or should I add a new `qinq` column?

**Comment by aherna** [comment]
> @aherna any thoughts on how to depict the QinQ setting for a VM in `vm info`? Should I modify the existing `vlan` column to include `qinq` for a particular VLAN? Or should I add a new `qinq` column?

hmm since its applied at the interface level maybe it should be added as a new column with all the participating megataps in qinq for that vm?

**Comment by activeshadow** [comment]
@aherna okay so maybe something like this?

```
$> mm .column qinq vm info
host       | qinq
shadowarch | [mega_tap1 (102)]
```

**Comment by aherna** [comment]
yea perfect

**Comment by activeshadow** [comment]
@aherna in that case, I think this PR is ready for you to review and test as well.

**Review by aherna — APPROVED** [review]
LGTM

**Comment by activeshadow** [comment]
@aherna I squashed the commits for this PR so feel free to merge at your convenience.

**Pull request merged**
