### PR TITLE
protonuke:  add irc support

### LINKED ISSUE #622: protonuke: add IRC client
Hey guys, let's hear some chatter out there.

### PR DESCRIPTION
**Pull request by x64x6a**
This adds IRC client and server support to `protonuke`.

The clients will attempt to communicate with one another using Markov chains.  The chains can be fed by the default 'lorem ipsum' text or from a user supplied file.  Markov chain algorithm was found in the Go source documentation as an example.

I added 2 projects to vendor:  `go-ircevent` and `goircd`

The IRC client uses `go-ircevent` while the irc server uses `goircd`.  It should be noted that a few changes have been made to these packages, so that they could work well with `protonuke`.  

It might be desired to simply add these packages' functionality to `protonuke` and remove the dependencies.

---

@jcrussell any changes or is everything perfect?
@djfritz 

Should close #622

### CODE REVIEW

**Comment by csymonds** [comment]
Resurrected. I would like to see protonuke support irc traffic

**Review by chengsteven — DISMISSED** [review]
lgtm

**Comment by aherna** [comment]
@chengsteven @csymonds Need to add IRC to reporting metrics, update a section in protonuke article

**Comment by chengsteven** [comment]
@aherna please review again

**Review by csymonds — APPROVED** [review]
LGTM

**Pull request merged**
